### ISSUE TITLE
Case conflicts (Day One)

### ISSUE THREAD

**Issue by bitic** [maebert/jrnl#259]
Hi,

Using jrnl 1.8.2 I launched the command: jrnl --edit

and it opened my Day One entries (my only journal) in a big file in Emacs (my editor).

As I didn't want to edit the whole journal, I quit Emacs (C-x C-#). 

This duplicated every entry in my journal with a Case Conflicted file.

I'm using
Python 2.7.3 in Debian 3.2.60-1+deb7u1 x86_64

**Comment by nikvdp** [comment]
@maebert This issue was fixed in PR #325, should be safe to close
