### ISSUE TITLE
deletes journal when I change my config

### ISSUE THREAD

**Issue by wfalkwallace** [maebert/jrnl#291]
anytime I change my config file (even if I just overwrite .jrnl_config with an identical .jrnl_config) and I run a jrnl command it empties out my preexisting jrnl file. That's a huge bummer. I get it for encrypted jrnls, maybe, but unencrypted too?

**Comment by raimondi1337** [comment]
This is happening to me right now. The first time I create a new entry after editing the date format in config, the new entry overwrites all of journal.txt
