### ISSUE TITLE
No default configuration for 2.0rc1

### ISSUE THREAD

**Issue by gcgoogle** [maebert/jrnl#297]
When running jrnl after just installing it, it doesn't work because a configuration file is not present, and it gives no further information about to how set one up, and just creating a blank file doesn't work because the YAML parser fails. jrnl 2.0 should either have a default configuration (like version 1 did) or it should explain how to create one.

**Comment by flight16** [comment]
This issue appears to be resolved by Maebert's April 4th commit.
