### ISSUE TITLE
Option to not use first sentence as title

### ISSUE THREAD

**Issue by mrcranky01** [maebert/jrnl#311]
When you use jrnl to edit DayOne entries (and possible when you use it for normal entries) it treats the first sentence in your entry as a title, and inserts a linebreak after the first period. In DayOne, it is optional to treat the first line as a title, so it would be nice to have a matching option in jrnl to not assume the first sentence is a title, and thus to not insert a linebreak after the first sentence.

**Comment by flight16** [comment]
I am for this as well.  So the output would look like the following?

2015-04-03 23:26 This is my first sentence.  And the rest keep going on the same line until I start a new line.

Then the rest continues down here.

**Comment by jotrk** [comment]
I'd like to see this feature as well. Please implement it.
Currently I have to always re-edit my jrnl entries to avoid the title sentence, which is kinda annoying.

**Comment by maebert** [comment]
This is fixed in 79fa9c5.
