### ISSUE TITLE
No support for variable length dates

### ISSUE THREAD

**Issue by vbomedeiros** [maebert/jrnl#317]
I set up my timeformat to be "%A, %d %b %Y, %H:%M", so I can get date strings like "Saturday, 29 Nov 2014, 18:20".

To my surprise, this totally broke my journal on my second day of usage. I read the code and found out this piece of code that assumes all dates will always have the same length. Not sure what would be a good solution for this problem.

```
        # Entries start with a line that looks like 'date title' - let's figure out how
        # long the date will be by constructing one
        date_length = len(datetime.today().strftime(self.config['timeformat']))
```

**Comment by flight16** [comment]
I agree using parenthesis or brackets to enclose the timestamp would be a nice way to allow better date format customization.  Ideally an option so users can opt-in.  Or should it be forced across the board and handled in the 2.0 journal upgrade?

@maebert What do you think?

**Comment by maebert** [comment]
I'm actually all for `[...]` and handling this in the 2.0 upgrade.
