### ISSUE TITLE
Lose journal when date format is modified

### ISSUE THREAD

**Issue by seinfield** [maebert/jrnl#318]
I managed to lose my journal when i had modified the date format (similar to issue #291).  This is discovered while testing another problem.
I have an existing journal.
Here are the steps:
1.  Modify the date format to "%A, %d %b %Y, %H:%M" from the default in the config file.
2. ./jrnl --edit
3. file is now empty.  Even when if i were to exit without saving, the file is already emptied out.  I use vim for my editor.

**Comment by maebert** [comment]
This is fixed on jrnl 2.0 :)
