### ISSUE TITLE
'No such file or directory' on launch when using Sublime Text 3 as editor.

### ISSUE THREAD

**Issue by Hendeca** [maebert/jrnl#324]
Hello!

Just for some background info, I installed jrnl via homebrew and I'm also using the home-brew version of python and pycrypto. I'm also running Mac OS X Yosemite. Whenever I try to use the jrnl command, I get the following error:

```python
melchior$ jrnl
Traceback (most recent call last):
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.7', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 190, in run
    raw = util.get_text_from_editor(config)
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/util.py", line 123, in get_text_from_editor
    subprocess.call(config['editor'].split() + [tmpfile])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**UPDATE:**
I solved this problem! I was using a symbolic link to /Applications/Sublime Text.app/Contents/SharedSupport/bin/subl that was in the folder ~/bin (which I had added to my path). So even though I could launch Sublime Text by typing 'subl' on the command line, when I used "subl -w" as my editor value in the ~/.jrnl_config file, I was getting the error. The solution was to include the full path to the alias AKA '~/bin/subl -w'

**Comment by jcouturier** [comment]
I've having the same issue, but `~/bin/subl -w` isn't working either. I get the same "No such file..." error. Any ideas?

**Comment by iggyvolz** [comment]
Try running: 
```bash
readlink -f "`which subl`"
```
That should give you the full path to your sublime binary - use that path to give you your path to subl.  For example, if the code gives you /usr/local/bin/subl, you will want to use /usr/local/bin/subl -w in your jrnl config.

**Comment by jcouturier** [comment]
Thanks @iggyvolz 

I'm on OSX (Mavericks), so there is no native readlink. I've installed coreutils, which has `greadlink`. And `greadlink -f "which subl"` returns `/Users/[my username]/which subl`

I can do `greadlink -f "which cheeseandbacon"` and it'll return `/Users/[my username]/which cheeseandbacon`
So something's amiss with greadlink.

I've tried adding my full path to the binary in .jrnl_config:

`"editor": "/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -w",`

but get the same "No such file..." error.

**Comment by Hendeca** [comment]
@jcouturier Does your subl binary work independent of jrnl? I found that on another computer I had to change the editor to just "subl -w" despite the fact that it was in ~/bin/subl

I am guessing you've already tried that, but just thought I'd ask!

**Comment by jcouturier** [comment]
@Hendeca Yep, all of these work and launch Sublime, with or without the `-w` flag:

```
$ subl
$ ~/bin/subl
$ /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
```

**Comment by iggyvolz** [comment]
@jcouturier Notice the backticks inside the quotes:
```bash
greadlink -f "`which subl`"
```

Essentially, you're running which subl, which gives you the path to your subl binary, and then passing it to readlink (or in your case, greatlink)

**Comment by jcouturier** [comment]
@iggyvolz Ah, I see. In that case, which is returning empty. Here's a direct copy/paste from my terminal:

```
GOON [~] $ greadlink -f "`which subl`"
GOON [~] $ 
```

**Comment by iggyvolz** [comment]
That's peculiar.  What does ```which subl``` alone return?

**Comment by jcouturier** [comment]
@iggyvolz It returns empty:
```
GOON [~] $ which subl
GOON [~] $ 
```

**Comment by iggyvolz** [comment]
That's so wierd... it seems the binary simply does not exist.  But just running subl does, correct?  In the same session that which subl returns empty?

How did you install the subl binary?  The only way I could think of that it wouldn't show to which is if it was a function inside a rc file.

**Comment by Hendeca** [comment]
@jcouturier Well, it's probably worth a try to delete your symlinks and relink from the Sublime Text package. Might even want to go so far as to re-download Sublime Text and grab the subl binary from the mounted .dmg file. Maybe just replace the one in your current Sublime Text package and relink. I guess that advice is equivalent to "turn it off then turn it back on" but it might work!

**Comment by jcouturier** [comment]
Fixed, and working now!
You were right, an alias in my .bash_profile was causing this. I had a `subl` alias pointing to `~/bin/subl`. The symlink was fine, but jrnl didn't like the profile alias. I remove that, then added `/Users/jeff/bin` to my PATH and that did the trick.

Thanks @Hendeca and @iggyvolz !

**Comment by jfonte** [comment]
Hi everyone. I'm having a similar issue and can't seem to find the root cause. Can someone offer some help/insight? 

**What's happening:** I type ```jrnl``` and ```subl``` is not being called. I'm basically getting the default behavior as if I had not modified the editor setting in the ```.jrnl_config``` file.

**Considerations:**

- My path in my ```~/.bashrc``` includes ```~/Users/ghost/bin``` (which is where my symlink for Sublime is).
-This is my ```.jrnl_config```:

```
{
  "linewrap": 79,
  "timeformat": "%Y-%m-%d %H:%M",
  "default_hour": 9,
  "tagsymbols": "@",
  "encrypt": true,
  "journals": {
    "default": "/Users/ghost/Downloads/jrnl-test/journal.txt"
  },
  "editor": "subl -w",
  "default_minute": 0,
  "highlight": true
}
```

Any ideas?
