### ISSUE TITLE
Windows temp file error

### ISSUE THREAD

**Issue by christianmlong** [maebert/jrnl#327]
On Windows 8.1, when I'm typing an entry, the file is shown as read-only in vi. When I try to save and quit, I get this error.

    WindowsError: [Error 32] The process cannot access the file 
    because it is being used by another process: 
    'c:\\users\\user~1\\appdata\\local\\temp\\jrnlxqjnzz.txt'

jrnl version 1.9.8 has the error
jrnl HEAD 15ef974 has the error

jrnl version 1.8.6 works fine
jrnl version 1.9.3 works fine
jrnl version 1.9.6 works fine

jrnl version 1.9.7 fails ( "AttributeError: 'tuple' object has no attribute 'replace'")

I installed jrnl HEAD like this

    pip install -e git+git@github.com:maebert/jrnl.git@15ef9749ae497b594b2a325c6ea897a8572d5bc6#egg=jrnl-master

**Comment by izio1** [comment]
Same problem when using Notepad++ as external editor and jrnl v 1.9.8
The error is preventing that the entries via notepad++ gets added to the journal.

**Comment by notbalanced** [comment]
There is a pull request #323 which fixes this issue. Basically the jrnl script has a handle open on the temp file that it needs to close.

**Comment by maebert** [comment]
Pull request merged into 2.0 - closing this issue.
