### ISSUE TITLE
jrnl Android app

### ISSUE THREAD

**Issue by orschiro** [maebert/jrnl#329]
Hi @maebert,

Many thanks for developing `jrnl`!

> For personal use, make it a good habit to write at least 20 words a day. Just to reflect what made this day special, why you haven’t wasted it.

Taken from your documentation page, I would like to follow this advice. Since I am frequently on my Android device, I was wondering whether there is an Android client that can link to the journal file in my shared Dropbox folder?

Are there any approaches to use jrnl from an Android device?

Warmly,

Robert

**Comment by teranex** [comment]
@orschiro have a look at [Journal with Narrate](https://play.google.com/store/apps/details?id=com.datonicgroup.narrate.app).  It uses the Day One format to store journalling entries, which `jrnl` can also read (https://maebert.github.io/jrnl/advanced.html#dayone-integration).

There is only one small issue for now (see #332): when you delete an entry in Narrate it creates a 'deleted' directory inside the entries directory, which makes `jrnl` crash. Simply removing the deleted directory solves that though.

**Comment by maebert** [comment]
Thanks for the recommendation @teranex, I haven't heard of Narrate yet and will check it out myself :) @orschiro, let us know whether that works for you!

**Comment by orschiro** [comment]
@teranex 

Thank you very much for the tip! Trying to set it up correctly. I created an entry on my Android. The entry was synced to my Dropbox to the following folder:

```
❯ l "/home/orschiro/Dropbox/Apps/day one/journal.dayone/entries"
total 1M
drwxr-xr-x 2 orschiro users 1M 2015-02-10 23:39:03.000000000 +0100 deleted
-rw-r--r-- 1 orschiro users 1M 2015-02-10 23:39:07.000000000 +0100 454B0D9C18B94C82A530B7FF55D13A7B.doentry
```

I added the path to my config accordingly:

```
  "journals": {
    "default": "/home/orschiro/Dropbox/Notebook/Journal/journal.txt",
    "dayone": "/home/orschiro/Dropbox/Apps/day one/journal.dayone"
  },
```

However, `jrnl -from 2015` does not show my latest entry.

**Comment by maebert** [comment]
Try `jrnl dayone -from 2015` -- `jrnl -from 2015` will only look in your default journal.

**Comment by orschiro** [comment]
```
❯  jrnl dayone -from 2015
Traceback (most recent call last):
  File "/usr/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/lib/python3.4/site-packages/jrnl/cli.py", line 189, in run
    journal = DayOneJournal.DayOne(**config)
  File "/usr/lib/python3.4/site-packages/jrnl/DayOneJournal.py", line 27, in __init__
    super(DayOne, self).__init__(**kwargs)
  File "/usr/lib/python3.4/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/lib/python3.4/site-packages/jrnl/DayOneJournal.py", line 33, in open
    with open(filename, 'rb') as plist_entry:
IsADirectoryError: [Errno 21] Is a directory: '/home/orschiro/Dropbox/Apps/day one/journal.dayone/entries/deleted'
```

I didn't create the folder `deleted` myself. It is created by Narrate automatically.

**Comment by orschiro** [comment]
There is no option to prevent `narrate` from creating a `deleted` folder in the root journal folder that contains all the journal entries. Is it possible for `jrnl` to ignore the deleted folder or generally any folder in the root folder that is pointing to `"dayone"?

**Comment by teranex** [comment]
@orschiro that is basically what i reported in #332  ;)

**Comment by orschiro** [comment]
@teranex 

Ups, sorry that I didn't notice this one. :P

**Comment by taylansengul** [comment]
the easiest way is to use ifttt with service append to a text file in Dropbox. Creates a homescreen widget which takes a note and appends it to a text file in dropbox with a timestamp.

**Comment by undying-fish** [comment]
Interested in this one too. I'm thinking it's possible to use termux for it, given that it installs via pip, but it's got some dependencies of its own so that might be a naive guess.

**Comment by justinkelly** [comment]
fyi `jrnl` can be install in `termux` on `android`, you just need to install a few other things first -r efer below for the install steps

```
apt-get install python-dev
apt-get install libffi-dev
apt-get install openssl-dev
pip install jrnl
```

**Comment by tototoben** [comment]
Having some problems with Termux, the mentioned dependencies seem fine:

```
$ apt-get install python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-dev is already the newest version (3.6.3).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
$ apt-get install libffi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libffi-dev is already the newest version (3.2.1-2).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
$ apt-get install openssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssl-dev is already the newest version (1.0.2m).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
```

But getting this error:
```
Using cached cffi-1.11.2.tar.gz
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-8g5m6oof/cffi/
```
@justinkelly Perhaps you have some insight what might be happening here and how to overcome it?

**Comment by justinbass** [comment]
Should be mentioned that jrnl[encrypted] does not work in termux due to pycrypto needing gcc for installation (gcc was apparently removed some time ago due to maintenance burden). Compiling pycrypto from source (with clang) won't work due to /bin/sh not being in place.

**Comment by infomofo** [comment]
I know this thread is a few months old now, but @tototoben 's steps are not working for me on the latest Termux (version 0.60).

The versions have updated a little so I am installing python-dev (3.6.5), libffi-dev(3.2.1-2) and openssl-dev (1.0.2o).

When I type `pip install jrnl`

I get the same error trace that tototoben pasted previously, although with an updated cffi version

```
Using cached cffi-1.11.5.tar.gz
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-s9wqfgc2/cffi/
```

Any ideas what might have changed recently that is breaking this toolchain again? I'm new to Termux so any advice on how to debug and remedy this issue would be greatly appreciated.

**Comment by msdos** [comment]
@infomofo install `clang` and `libcrypt-dev`, follow https://github.com/maebert/jrnl/issues/329#issuecomment-348468929, then `apt update && apt upgrade`, `jrnl[encrypted]` can be installed.

Source: https://github.com/termux/termux-packages/issues/2430

**Comment by msdos** [comment]
I didnt test the encryption myself, please check https://github.com/maebert/jrnl/issues/329#issuecomment-354508795.
