### ISSUE TITLE
DayOne Integration for non Mac OS X Systems

### ISSUE THREAD

**Issue by tristan-k** [maebert/jrnl#338]
Hi there,

I'm running Ubuntu 14.04 and installed jrnl with pip successfully. I read the documentation at http://maebert.github.io/jrnl/advanced.html#dayone-integration and followed the instruction for .jrnl_config. Here is my config:

```
{
  "default_hour": 9, 
  "timeformat": "%Y-%m-%d %H:%M", 
  "linewrap": 79, 
  "encrypt": false, 
  "editor": "", 
  "default_minute": 0, 
  "highlight": true, 
  "journals": {
    "default": "/home/tristank/journal.txt",
    "dayone": "/home/tristank/Text/journal/tristank.dayone"    
  }, 
  "tagsymbols": "@"
}
```

```
$ jrnl 
[Compose Entry; press Ctrl+D to finish writing]
Test
[Entry added to default journal]
```

The Entry will be added to journal.txt but not to the dayone folder.

Is the DayOne Integration just available for Mac OS X?

**Comment by maebert** [comment]
Hi Tristan,

in the current setup, you will have *two* journals - one using
