### ISSUE TITLE
Exception when running 'jrnl' without arguments with multiple journals

### ISSUE THREAD

**Issue by flight16** [maebert/jrnl#343]
<pre>
kaeru:~ flight16$ jrnl 
Traceback (most recent call last):
  File "/usr/local/Cellar/jrnl/1.9.6_2/libexec/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.6', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.6_2/lib/python2.7/site-packages/jrnl/cli.py", line 159, in run
    config['journal'] = os.path.expanduser(os.path.expandvars(config['journal']))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 293, in expandvars
    if '$' not in path:
TypeError: argument of type 'NoneType' is not iterable
kaeru:~ flight16$ jrnl -ls
tm
code
health
kaeru:~ flight16$ 
</pre>

I would expect to see --help output.

Here is my config

<pre>
kaeru:~ flight16$ cat ~/.jrnl_config 
{
  "default_hour": 22, 
  "timeformat": "%Y-%m-%d %H:%M", 
  "linewrap": 79, 
  "encrypt": false, 
  "editor": "", 
  "default_minute": 0, 
  "highlight": true, 
  "journals": {
    "code":   "/Users/flight16/Documents/Journals/code.txt",
    "tm":     "/Users/flight16/Documents/Journals/tm.txt",
    "health": "/Users/flight16/Documents/Journals/health.txt"
  }, 
  "tagsymbols": "@"
}
kaeru:~ flight16$ 
</pre>

This touches the same code path as #340 so it could be resolved as a part of that issue.

**Comment by maebert** [comment]
Good point! thanks

**Comment by maebert** [comment]
Fixed it!
