### ISSUE TITLE
Git support

### ISSUE THREAD

**Issue by masterkorp** [maebert/jrnl#352]
This tool is just plain awesome.

I would like to *automagically* commit my jornal entries to git. Is git support a feature on the roadmap or anything like that ?

If not some support for hook scripts would be nice too. I could achive what I need without adding too much complexity to the code-base.

Regards

**Comment by maebert** [comment]
jrnl is written to live happily in a shell pipeline. So you can easily do something like this by writing a simple script in your `~/.bash_profile` or `~/.bashrc`:

```bash
jrnlgit () {
    jrnl;
    pushd path/to/your/jrnl;
    git add journal.txt;
    git commit -m "Added a new entry";
    git push;
    popd;
}
```

Note that jrnl 2.0 will also support individual files for entries, so you can do `git add -a` instead.
