### ISSUE TITLE
Tag filtering results in an error

### ISSUE THREAD

**Issue by flight16** [maebert/jrnl#353]
I am trying to filter on a tag using the syntax [documented here](https://maebert.github.io/jrnl/usage.html#using-tags), but get nothing but errors.

<pre>
$ jrnl org  -and @atag
usage: jrnl [-h] [-v] [-ls] [-from DATE] [-until DATE] [-on DATE] [-and]
            [-starred] [-n [N]] [--short] [--tags] [--export TYPE] [-o OUTPUT]
            [--encrypt [FILENAME]] [--decrypt [FILENAME]] [--edit]
            [[...]]
jrnl: error: unrecognized arguments: @atag
</pre>

Also tried the following with no succes:

<pre>
$ jrnl org -and atag
$ jrnl org  -n 5 -and @atag
$ jrnl dayone -and @atag
</pre>

**Comment by offthecuff** [comment]
Looks like a command line parsing issue. The command will work if the -and is last _or_ if there's no journal name given.
```bash
$ jrnl org @atag -and
$ jrnl -and @atag
```

**Comment by flight16** [comment]
Thanks for verifying.  I think I know the section of code causing this issue.

This is another example of why I think removing some magic and replacing it with explicit commands would be beneficial. (See related comment https://github.com/maebert/jrnl/issues/282#issuecomment-92806327 )

**Comment by maebert** [comment]
That's an interesting issue, thanks for pointing that out. I agree there should be an explicit `-filter` or `-search` argument (not sold on commands yet ;-)
