### ISSUE TITLE
Cannot turn off insertion of `\n` into my entries.

### ISSUE THREAD

**Issue by rory** [maebert/jrnl#360]
I use jrnl on my Ubuntu Linux machine, mostly from the command line with the `jrnl` command, (e.g. `jrnl "Finished doing X"`). However it will often insert newlines (`\n`) into my entries in order to wrap the long lines. I'd like to turn this off, so that what is stored is only what I enter on the command line (or rarely via `vim`).

My `~/.jrnl_config` is:

    {
      "default_hour": 9, 
      "timeformat": "%Y-%m-%d %H:%M", 
      "linewrap": false, 
      "encrypt": false, 
      "editor": "gvim -f", 
      "default_minute": 0, 
      "highlight": false, 
      "journals": {
        "default": "/home/rory/journal.txt"
      }, 
      "tagsymbols": "@#"
    }

Here's an example of what I'm talking about:

    $ jrnl "This is a really long line to test that jrnl is not wrapping line. I want all this to be entered exactly without inserting any new lines at all at all at all. well did this work?"
    [Entry added to default journal]
    $ jrnl -1
    2015-06-03 11:07 This is a really long line to test that jrnl is not wrapping line.
    I want all this to be entered exactly without inserting any new lines at all at all at all. well did this work?

    $ jrnl -1 | od -c
    0000000   2   0   1   5   -   0   6   -   0   3       1   1   :   0   7
    0000020       T   h   i   s       i   s       a       r   e   a   l   l
    0000040   y       l   o   n   g       l   i   n   e       t   o       t
    0000060   e   s   t       t   h   a   t       j   r   n   l       i   s
    0000100       n   o   t       w   r   a   p   p   i   n   g       l   i
    0000120   n   e   .  \n   I       w   a   n   t       a   l   l       t
    0000140   h   i   s       t   o       b   e       e   n   t   e   r   e
    0000160   d       e   x   a   c   t   l   y       w   i   t   h   o   u
    0000200   t       i   n   s   e   r   t   i   n   g       a   n   y    
    0000220   n   e   w       l   i   n   e   s       a   t       a   l   l
    0000240       a   t       a   l   l       a   t       a   l   l   .    
    0000260   w   e   l   l       d   i   d       t   h   i   s       w   o
    0000300   r   k   ?  \n  \n
    0000305
    $ tail -3 ~/journal.txt 

    2015-06-03 11:07 This is a really long line to test that jrnl is not wrapping line.
    I want all this to be entered exactly without inserting any new lines at all at all at all. well did this work?
    $ tail -3 ~/journal.txt  | od -c
    0000000  \n   2   0   1   5   -   0   6   -   0   3       1   1   :   0
    0000020   7       T   h   i   s       i   s       a       r   e   a   l
    0000040   l   y       l   o   n   g       l   i   n   e       t   o    
    0000060   t   e   s   t       t   h   a   t       j   r   n   l       i
    0000100   s       n   o   t       w   r   a   p   p   i   n   g       l
    0000120   i   n   e   .  \n   I       w   a   n   t       a   l   l    
    0000140   t   h   i   s       t   o       b   e       e   n   t   e   r
    0000160   e   d       e   x   a   c   t   l   y       w   i   t   h   o
    0000200   u   t       i   n   s   e   r   t   i   n   g       a   n   y
    0000220       n   e   w       l   i   n   e   s       a   t       a   l
    0000240   l       a   t       a   l   l       a   t       a   l   l   .
    0000260       w   e   l   l       d   i   d       t   h   i   s       w
    0000300   o   r   k   ?  \n
    0000305

As you can see, I entered a really long entry via the command line, without any newlines, and jrnl added the newlines after the sentence breaks.

Is it possible to turn off this feature?

**Comment by flight16** [comment]
What your describing is how jrnl handles titles.  The first sentence is always assumed to be the title and gets placed on its own line.  If you make the second sentence 1000 characters, the second sentence should all be placed on its own line.

There is a feature request to make this behavior an option here #311, although it is filed only for DayOne journals.  

At first I didn't like this behavior, but I've grown to like it, combined with jrnl --short -n 5

**Comment by maebert** [comment]
I'm making title treatment optional in 2.0 -- it will be saved exactly as entered.

**Comment by sloria** [comment]
I'm still seeing jrnl force a new-line after the first `.` (or other sentence delimiter). Did this regress?

**Comment by wren** [comment]
@sloria Not sure. Can you please start a new issue with some details about what you're seeing?  It's easier for us to track issues this way. Thank you!
