### ISSUE TITLE
Can't save new entry while using notepad++ on Windows 8

### ISSUE THREAD

**Issue by castor-troy** [maebert/jrnl#361]
I get the following error.

    Microsoft Windows [Version 6.3.9600]
    (c) 2013 Microsoft Corporation. All rights reserved.
    
    C:\Windows\system32>jrnl
    Password:
    Traceback (most recent call last):
      File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\python34\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "c:\python34\scripts\jrnl.exe\__main__.py", line 9, in <module>
      File "c:\python34\lib\site-packages\jrnl\cli.py", line 207, in run
        raw = util.get_text_from_editor(config)
      File "c:\python34\lib\site-packages\jrnl\util.py", line 136, in get_text_from_
    editor
        os.remove(tmpfile)
    PermissionError: [WinError 32] The process cannot access the file because it is
    being used by another process: 'C:\\Users\\Username\\AppData\\Local\\Temp\\jrnl3448
    2u6f.txt'
    
    C:\Windows\system32>

**Comment by flight16** [comment]
@castor-troy What version of jrnl are you using?  Is the behavior the same for any external editor, or just notepad++?

**Comment by castor-troy** [comment]
It happens with regular "notepad" as well. I don't know how to check the version. I downloaded the latest version from the site.

**Comment by flight16** [comment]
Try the 2.0 rc branch.  According to #327, there is a fix in there.

**Comment by castor-troy** [comment]
Could you help me update it? I am pretty new to all this stuff. I installed the original version using pip command on windows. How can I upgrade it to 2.0?

**Comment by castor-troy** [comment]
Well, I managed to upgrade it somehow and I'm glad to report that it's working now.

**Comment by flight16** [comment]
Good to hear!

Hopefully @maebert can eventually find time to release the 2.0 branch in the middle of all his globetrotting so people stop hitting this bug. ;)

**Comment by maebert** [comment]
@castor-troy Excellent! I'm a bit overwhelmed with work but I really really want to ship 2.0 this month!
