### ISSUE TITLE
Timeformat is too fragile

### ISSUE THREAD

**Issue by Jefficus** [maebert/jrnl#365]
I tried changing the timeformat in ~/.jrnl_config to "" (because I don't care about the dates or times and don't want them cluttering up the output) but now jrnl shows no entries at all. I then tried changing it to simply ">" and then "%d", but each time, no records were displayed. It seems that jrnl expects all the datetime elements to be present in the format string, which severely limits its flexibility.

**Comment by flight16** [comment]
This might be addressed in the 2.0 branch, but I don't have time to check this morning.  I seem to recall a similar issue being reported before.

**Comment by maebert** [comment]
This is solved in 2.0 :) Closing this for 1.x
