### ISSUE TITLE
Asymmetric encryption

### ISSUE THREAD

**Issue by Niols** [maebert/jrnl#371]
Hi,

I'm using jrnl with password encryption. But I'm tired of entering my password each time. Would there be a way to add asymmetric encryption ?

So that we wouldn't need to enter password to write new things, but we would to read them…

I don't know if that's feasible, easy, hard, usefull, weakening the security… But that was just an idea.

**Comment by drkarl** [comment]
Maybe through an agent like the ssh-agent?

**Comment by maebert** [comment]
Hi @Niols, thanks for the suggestion (and sorry for the long hiatus). You can save your password in your keychain on most systems, does that remedy the issue? Asymmetric encryption is definitely out of scope for `jrnl` in the foreseeable future.
