### ISSUE TITLE
Exporting jrnl as text shouldn't style entries

### ISSUE THREAD

**Issue by dufferzafar** [maebert/jrnl#373]
Running `jrnl @sometag --export text` shouldn't try to print text in color (escape codes) and the pipe characters. 

My rationale is that when I'm exporting something in text I'd want it to use it someplace else, and there I'll have to remove those pipe characters and the color escape codes.

Honestly, `--export markdown` feels much better than text, because no color codes/pipes are involved there.

**Comment by maebert** [comment]
Completely agree! Will be fixed.
