### ISSUE TITLE
jrnl fails to read dayone .. due to presence of dayone 'deleted' folder

### ISSUE THREAD

**Issue by chuxau** [maebert/jrnl#385]
I am trying to read a dayone file created (and encrypted) in osx .. and sync'ed to dropbox .. from a debian workstation .. 

I get the following error, which suggests it is a simple case of the existence of a 'deleted' directory which is a standard dayone sub-directory within the 'entries' directory .. 

<pre>
~/b$ jrnl dayone -n 3
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/jrnl/cli.py", line 189, in run
    journal = DayOneJournal.DayOne(**config)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/DayOneJournal.py", line 27, in __init__
    super(DayOne, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/jrnl/DayOneJournal.py", line 33, in open
    with open(filename, 'rb') as plist_entry:
IOError: [Errno 21] Is a directory: u'/home/moi/Dropbox/Apps/Day One/Journal.dayone/entries/deleted'
</pre>

I was wondering how jrnl would handle the fact that dayone is encrypted, but we never really got to that .. 

Any suggestions ?

Thanks in advance 

PS: This is on debian jessie (8.x)
~/b$ jrnl --version
jrnl version 1.9.8

**Comment by flight16** [comment]
Reported previously in #332 with a fix submitted to the 2.0 branch.  It hasn't had any activity for about 5 months so it would be faster to install from source or apply the fix locally to master yourself.

**Comment by chuxau** [comment]
flight16, thanks for info and the link to the other resolved issue .. my 'deleted' folder is also there due to using narrate on android .. 

Hate to build from sources (instead of relying on pip) though .. and pip still has 1.9.8 as the latest .. guess I have no choice but to apply a local fix until pip is updated .. 

Thanks again ..

**Comment by maebert** [comment]
Sorry for the Hiatus, 2.0 is back on track!
