### ISSUE TITLE
Server-based JNRL

### ISSUE THREAD

**Issue by robinweide** [maebert/jrnl#388]
Would it be possible to store the journal on a server? So that mulitple people can work/look inside the same journal?

**Comment by MinchinWeb** [comment]
In it's simplest form, `jrnl` has a text file backend. So if you were to sync the data file between computers, you'd be able to access and update it from each of those computers. I currently sync `jrnl` this way (using Dropbox) between my desktop and laptop.

I'm not sure what issues you might run into if two people were to try and update the data file at the same time. In that case, you might consider the DayOne storage backend, that stores each entry as a separate data file. This way, you shouldn't have any issues unless two people try to update the same entry at the same time.

What are you imagining for a workflow?

**Comment by maebert** [comment]
Hi @robinweide, in addition to this, look at #352 to see how you can simply wrap `jrnl` so that entries are committed to a git repository.
