### ISSUE TITLE
suggested HISTIGNORE command in docs glob expands to include directory contents

### ISSUE THREAD

**Issue by derelk** [maebert/jrnl#394]
The docs suggest setting `HISTIGNORE="jrnl *"`. Unfortunately regardless of whether this is preceded by `export` and whether it's in a shell or in `.bashrc`, the asterisk is treated as a glob and `HISTIGNORE` will contain `jrnl` followed by everything in the current directory. This still seems to prevent jrnl commands from ending up in history, but doesn't seem ideal to have all that extra stuff in there. I couldn't find a way to escape the asterisk, but since colon is the HISTIGNORE delimiter, this works:
`HISTIGNORE="jrnl *:"`

**Comment by maebert** [comment]
Thanks for pointing that out - fixed for the 2.0 release.
