### ISSUE TITLE
what does jrnl -s do?

### ISSUE THREAD

**Issue by gauteh** [maebert/jrnl#404]
I tried doing `jrnl -s` to search, I don't know if that is implemented, but it does not seem to be listed in `-h`.

**Comment by philipsd6** [comment]
I'm using the latest 2.0-rc1 branch, but I assume it's the same in the current 1.0:

~~~
jrnl -h
…snip…
Export / Import:
  Options for transmogrifying your journal

  -s, --short           Show only titles or line containing the search tags
~~~

So, it's not search, it's the short option for short output (titles only.)

**Comment by gauteh** [comment]
Ah, that explains it. Not included here.
