### ISSUE TITLE
Cannot access jrnl files. No recommended backend was available

### ISSUE THREAD

**Issue by dastagg** [maebert/jrnl#407]
Running on ArchLinux.
The default jrnl file is encrypted.
What are the keyring backends it is looking for?

~ ❯❯❯ jrnl --edit                                                                                                                         ⏎
Traceback (most recent call last):
  File "/usr/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/lib/python3.5/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/lib/python3.5/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/lib/python3.5/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/lib/python3.5/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/lib/python3.5/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python3.5/site-packages/keyring/backends/fail.py", line 18, in get_password
    raise RuntimeError("No recommended backend was available")
RuntimeError: No recommended backend was available
~

**Comment by dantix** [comment]
Same, this happened after updating python-keyring to the latest version.

@dastagg, you can "fix" it via rollbacking python-keyring - `sudo pacman -U /var/cache/pacman/pkg/python-keyring-7.3-1-any.pkg.tar.xz`

**Comment by dastagg** [comment]
Thanks! That worked, but I'm not going to close this issue. Not sure why it doesn't work with python-keyring 8.2-1 so I'll leave this open and check the next time jrnl updates.

**Comment by maebert** [comment]
Thanks, I locked the version to 7.3 while figuring out how what's going on in 8.2.

**Comment by keegoid** [comment]
I'm also experiencing the same issue in Ubuntu 14.04 x64. I though I had fixed it by installing python-gpgme, but the problem has come back again after some upgrades.

**Comment by dastagg** [comment]
Just to follow-up:

Just upgraded python-keyring to 8.4.1-1 and python-keyrings-alt 1.1.2016123-1 and jrnl is working fine.

**Comment by hoptimusthreat** [comment]
This did the trick for me. 

`apt-get install python-keyring`
