### ISSUE TITLE
initial journal creation error in Ubuntu 15.10

### ISSUE THREAD

**Issue by keegoid** [maebert/jrnl#410]
I installed pip and the jrnl[encrypted] on a fresh install of Ubuntu 15.10 64-bit. I'm getting an error when I try to run it for the first time by typing jrnl in the terminal. I don't know what to do. Any help is greatly appreciated.

``` bash
~$ jrnl
Path to your journal file (leave blank for ~/journal.txt): 
Enter password for journal (leave blank for no encryption): 
Do you want to store the password in your keychain? [Y/n]
y
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/lib/python2.7/dist-packages/jrnl/cli.py", line 138, in run
    config = install.install_jrnl(CONFIG_PATH)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/install.py", line 76, in install_jrnl
    util.set_keychain("default", password)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/util.py", line 65, in set_keychain
    keyring.set_password('jrnl', journal_name, password)
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/fail.py", line 18, in get_password
    raise RuntimeError("No recommended backend was available. Install the "
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

**Comment by keegoid** [comment]
Tested in fresh installs of Ubuntu 14.04, 15.04 and 15.10.

To produce the error:
```bash
~$ sudo apt-get install pip
~$ sudo -i pip install jrnl[encrypted]
~$ jrnl
```

To fix the error (which was not readily apparent):
```bash
~$ sudo apt-get install python-gpgme
~$ jrnl
```

After installing python-gpgme, jrnl is able to store the encryption password in the keyring. I'm not sure why pip didn't install this dependency or at least alert me in the error message? It took me a while to track down this missing piece of the puzzle.

**Comment by ChristianAE** [comment]
@keegoid saldy for me (Ubuntu 16.10) your solution isn't working. Did you manage to get it running using Ubuntu 16.10?

**Comment by keegoid** [comment]
Thanks @ChristianAE , I also had to install keyrings.alt for it to work in Ubuntu 16.10. Plus I installed python-keyring using apt. Not sure which one did the trick for me, but glad it's working.
