### ISSUE TITLE
Quantum safe encryption

### ISSUE THREAD

**Issue by rxa254** [maebert/jrnl#414]
Seems like the AES CBC encryption is not safe against quantum computers using Shor's algorithm. Would it be possible to add an option to use one of the new quantum-safe encryption protocols so that our writing would remain secret for more than 20 years?

https://www.quantamagazine.org/20150908-quantum-safe-encryption/

**Comment by maebert** [comment]
In principle: yes. However since this will likely not become a problem within the next 20 years, this is rather low on my priority list. Let's revisit this in 2026?
