### ISSUE TITLE
Gnome keyring error

### ISSUE THREAD

**Issue by nocturnaltortoise** [maebert/jrnl#427]
I get this error whenever trying to do anything with jrnl.

/usr/lib/python2.7/site-packages/keyring/backends/Gnome.py:6: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring

According to this thread it's to do with python-keystoneclient: https://bugs.launchpad.net/python-keystoneclient/+bug/1517907

**Comment by maebert** [comment]
Can you try `pip install -U keyring` please?

**Comment by nocturnaltortoise** [comment]
That worked, I had an old version of keyring (5.0) and doing that installed version 9.0, thanks for the help.

**Comment by maebert** [comment]
Excellent!
