### ISSUE TITLE
Feature Request: Local Journals

### ISSUE THREAD

**Issue by garbotz** [maebert/jrnl#428]
Initialize a journal in current directory if it doesn't exist, and specify that local journal as if a config-based journal while in a directory.

Why do this? To have directly specified journals that are local to other project files, as opposed to keeping all journals in a central location alone. Using the same syntax as config-based journal manipulation shouldn't present problems, and is my possibly naive suggestion of how to implement.

.jrnl_config "config-based journals": 

``` json
"journals": {
    "default": "/Users/gm/default_jrnl.txt",
    "examplename": "/Users/gm/enjrnl.txt"
}
```

terminal:

```
$ pwd && ls
/Users/gm/projects/bigproject
project.xyz projectstuff.asd

$ jrnl log I wish I had a local journal for BigProject!
[Entry added to default journal]

$ jrnl -1
01:23:45 09:00 log I wish I had a local journal for BigProject!

$ jrnl log
[Journal created at /Users/gm/projects/bigproject/log.txt]

$ ls
log.txt  project.xyz projectstuff.asd

$ jrnl log Project start.
[Entry added to /Users/gm/projects/bigproject/log.txt journal]

$ jrnl This one will just be in default.
[Entry added to default journal]

$ cd .. && pwd && ls
/Users/gm/projects
bigproject  smallproject  laughs.yux

$ jrnl log Now still just to default.
[Entry added to default journal]

$ jrnl examplename Works just like config-based journal.
[Entry added to examplename journal]

```

(I apologize for any tactlessness, this is my first github post. jrnl.sh is much appreciated thank you!)

**Comment by maebert** [comment]
Welcome to Github, and thanks for sharing this idea! Just to make sure I understand you, you want an option that will, if active, look for a journal file in the current working directory?

What about having an `-j` parameter to explicitly specify which file to use, so you could do `jrnl -j my_journal.txt Hello world` to write to the `my_journal.txt` in the current directory. You could also set an alias like `jj="jrnl -j my_journal.txt"` so you won't have to type it every time.

**Comment by cohan** [comment]
You could set up a "project" or "this" file (name as desired) with a relative path - that seems to work

```
{
  "default_minute": 0,
  "journals": {
    "this": "./this.txt",
    "todo": "/home/me/todo.txt",
    "default": "/home/me/journal.txt"
  },
  "default_hour": 9,
  "timeformat": "%Y-%m-%d %H:%M",
  "tagsymbols": "@#",
  "editor": "",
  "linewrap": 79,
  "encrypt": false,
  "highlight": true
}
```

**Comment by maebert** [comment]
Ha, that's actually pretty clever @cohan. I'll add this to the documentation in future releases!
