### ISSUE TITLE
I just found what I was looking for

### ISSUE THREAD

**Issue by rallen-temp** [maebert/jrnl#438]
Creating a support ticket for.... SAYING THANK YOU !!!

As a developer who has been a client of talk-therapy for about a year, and who as part of that therapy has to keep a daily log of his mood, I must say, whoever wrote this just improved my life for much better.

Because I pretty much live 24/7 in the command line, this is the perfect way of keeping my daily mental health journal without leaving my favorite environment - the shell.

I am indebted. Hopefully one day I'll learn Python so that I can too contribute back to this wonderful project.

<3
- rallen

**Comment by maebert** [comment]
Hey Rallen, thank you so much for this, it means the world to me. Writing open-source software is fun, but feedback from users who are genuinely grateful is what makes it really worth it!

PS. If you journal a lot, i've got another (sadistic) tool for you: themostdangerouswritingapp.com

**Comment by Segdon** [comment]
www.themostdangerouswritingapp.com -->> brilliant! Straight to my bookmarks. Almost as brilliant as jrnl.
