### ISSUE TITLE
MacOS Sierra Keychain

### ISSUE THREAD

**Issue by wwwdata** [maebert/jrnl#445]
Hi,

I have a problem when trying to use the MacOS Sierra Keychain to store the journals password. I have installed jrnl via homebrew. Storing the Password in the keychain outputs the following error:

```sh
Do you want to store the password in your keychain? [Y/n]
Y
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.7', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 239, in run
    encrypt(journal, filename=args.encrypt)
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 78, in encrypt
    util.set_keychain(journal.name, password)
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/util.py", line 62, in set_keychain
    keyring.set_password('jrnl', journal_name, password)
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 37, in set_password
    raise PasswordSetError("Can't store password on keychain")
keyring.errors.PasswordSetError: Can't store password on keychain
```

**Comment by maebert** [comment]
Could you try `pip install -U keyring` ?

**Comment by wwwdata** [comment]
In order to do that I also had to install python via homebrew which I did. But this didn't change anything.

I then removed the homebrew installation of jrnl and also installed jrnl with pip. I now use the version `1.9.8`. Homebrew had the version `1.9.7`. The installation from pip works with the Keychain. Where does this version `1.9.8` come from? The latest release here on github also says `1.9.7`

**Comment by maebert** [comment]
1.9.8 should be the latest release on the 1.x branch - I don't maintain the homebrew formula myself, so it's fairly possible that it's out of date. Did that fix the issue?

**Comment by wwwdata** [comment]
Hm, we should check homebrew now I guess and upgrade that. Many users will install it via brew because they install everything with it.

**Comment by maebert** [comment]
Agreed, I'll get on to that!

**Comment by PeterLD** [comment]
@maebert any updates on getting the latest version on homebrew? I just tried pulling it and got `1.9.7`

**Comment by oschrenk** [comment]
What actually helped me was to go to keychain. Lock the Login keychain and then unlock it again
