### ISSUE TITLE
small change in jrnl_config will break all journall file

### ISSUE THREAD

**Issue by JosefMor** [maebert/jrnl#446]
after change
from
"timeformat": "%Y-%m-%d %H:%M", 
to
"timeformat": "%Y-%m-%d_%H:%M", 
all current content is removed
---
shared journals must be shared with absolutely the same config

**Comment by maebert** [comment]
Thanks for spotting this - this is is fixed in the upcoming 2.0 Branch!

**Comment by JosefMor** [comment]
Thanks for answer, problem is with every file without started "jrnl date header"
