### ISSUE TITLE
What's the best way to run jrnl to test while developing for it? 

### ISSUE THREAD

**Issue by abrahamneben** [maebert/jrnl#451]
I have jrnl installed with pip for personal use, so how can I develop jrnl without interfering with this pip installation?

**Comment by MinchinWeb** [comment]
I would look into using a [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/) and then installing your development version of jrnl into that.

Just be aware that both versions of jrnl will probably refer to the same configuration files, and therefore the same data files, so backup your jrnl data before you start messing around.

**Comment by maebert** [comment]
Hi @abrahamneben, thanks for joining jrnl. The best way to do this is to use virtualenvwrapper:

```
pip install virtualenvwrapper
mkvirtualenv jrnl
git clone https://github.com/maebert/jrnl.git
cd jrnl
pip install --editable .
```

The last command installs jrnl but makes it editable. Next time you work on it, do `workon jrnl` to activate the virtualn environment.
