### ISSUE TITLE
Installing on Ubuntu requires additional APT dependencies

### ISSUE THREAD

**Issue by k4kfh** [maebert/jrnl#452]
Hello, I tried to install on Xubuntu 16.04 and encountered some issues. I don't think it was an issue with ``jrnl``, rather it seems to be a dependency issue. The crypto library would not set up correctly (regardless of whether I tried ``jrnl`` or ``jrnl[encrypted]``) until I installed some additional dependencies. Now it works just fine. I think it'd be a good idea to add this to the documentation page. This is the command I used, borrowed from a StackOverflow post:

```
sudo apt-get install build-essential libssl-dev libffi-dev python-dev
```

Happy to post more information if necessary. This is an excellent program.

**Comment by maebert** [comment]
Awesome, I'll add that! Glad you got it to work.
