### ISSUE TITLE
Cannot create a journal.

### ISSUE THREAD

**Issue by MaralS** [maebert/jrnl#461]
Hi , here is the error message when I try to install jrnl on my system. (Windows 10)

```
C:\Users\Maral Sabbagh>pip install jrnl[encrypted]
Collecting jrnl[encrypted]
  Using cached jrnl-1.9.8.tar.gz
Collecting parsedatetime>=1.2 (from jrnl[encrypted])
  Using cached parsedatetime-2.2.tar.gz
Collecting pytz>=2013b (from jrnl[encrypted])
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting six>=1.6.1 (from jrnl[encrypted])
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting tzlocal>=1.1 (from jrnl[encrypted])
  Using cached tzlocal-1.3.tar.gz
Collecting keyring>=3.3 (from jrnl[encrypted])
  Using cached keyring-10.2-py2.py3-none-any.whl
Collecting pyreadline>=2.0 (from jrnl[encrypted])
  Using cached pyreadline-2.1.zip
Collecting colorama>=0.2.5 (from jrnl[encrypted])
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting python-dateutil>=2.2 (from jrnl[encrypted])
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting pycrypto>=2.6 (from jrnl[encrypted])
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 663kB/s
Collecting future (from parsedatetime>=1.2->jrnl[encrypted])
  Using cached future-0.16.0.tar.gz
Collecting pywin32-ctypes; sys_platform == "win32" (from keyring>=3.3->jrnl[encrypted])
  Using cached pywin32-ctypes-0.0.1.tar.gz
Installing collected packages: future, parsedatetime, pytz, six, tzlocal, pywin32-ctypes, keyring, pyreadline, colorama, python-dateutil, pycrypto, jrnl
  Running setup.py install for future ... error
Exception:
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 90: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files (x86)\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 90: invalid continuation byte
```

Thank you in advance for your help.
Kind regards

**Comment by MinchinWeb** [comment]
Python broke while trying to install the `futures` library. Try downloading it from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/), installing it, and then try install `jrnl` again.

**Comment by maebert** [comment]
Thanks for hopping in, @MinchinWeb. Did that solve the issue, @MaralS?

**Comment by MaralS** [comment]
@MinchinWeb : I uninstalled Python but I'm a little bit lost I'm a newbie. Which version can I install ? 
Thanks you !

**Comment by MinchinWeb** [comment]
@MaralS : Use Python 3.6.0 like you were. Use the 64 bit version if your computer supports that. That's probably the version I'd recommend.

Once you have Python installed, then you install `jrnl`:

- First download `futures` from the website link above. The actual file will be called `future‑0.16.0‑py3‑none‑any.whl`. Then install it from CMD:

        C: > pip install C:\path\to\downloads\future‑0.16.0‑py3‑none‑any.whl

- next try install installing `jrnl` again:

        C: > pip install jrnl

This will should install `jrnl`, but won't support encrypted journals. Encryption support relies on a package called `pycrypto`, which is a pain to install on Windows. If you require encryption, I would suggest you install the preview of version 2.0 of `jrnl`, which relies on a different encryption backend ([cryptography](https://cryptography.io/en/latest/)), which is much easier to install on Windows. I've been running this "preview" for the last probably two years without major issues. To install the preview of version 2.0, run:

    C: > pip install git+https://github.com/maebert/jrnl.git@2.0-rc1

(this probably requires GIT to be installed on your system, available [here](https://git-scm.com/download/win) if needed).

**Comment by immigrantsheep** [comment]
While trying to install the rc1 I'm getting fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory when he's trying to install cryptography. This is, cryptography was already install and jrnl removes it at the beginning of it's own installer.

**Comment by MaralS** [comment]
@MinchinWeb I tried to install Python but I still have the same error. I will write on a paper xD
