### ISSUE TITLE
Requirements for adding new entry in text editor

### ISSUE THREAD

**Issue by nman999** [maebert/jrnl#462]
It is nice to be in a computer with jrnl installed. If I dont have access to jrnl, can I still add a new entry in a regular text editor? what are the requirements for it to be read and correctly understood by jrnl later on? timestamp? do entries need to be in order?
thanks,

**Comment by maebert** [comment]
As long as you don't encrypt your journal, you can add entries with any text editor! Order doesn't matter, either. Just follow [the convention of the time stamps and titles](http://jrnl.sh/installation.html#quickstart) and jrnl will recognize the entry!
