### ISSUE TITLE
external editor opened with read only mode?

### ISSUE THREAD

**Issue by shaobozi** [maebert/jrnl#465]
I configured the external editor in configuration file:  "editor": "vim".  I use jrnl in powershell  Windows 10. After I type the **jrnl** command and press **Enter** , vim editor opens the tmp file in **read only** mode. So nothing could be saved to jrnl entries.  Did I do something wrong?

**Comment by notbalanced** [comment]
This has already been documented with #415 and pull request #416 fixes the issue.
