### ISSUE TITLE
jrnl: command not found

### ISSUE THREAD

**Issue by undying-fish** [maebert/jrnl#483]
`pip install jrnl`

```
Collecting jrnl
Collecting python-dateutil==1.5 (from jrnl)
Collecting tzlocal>=1.1 (from jrnl)
Collecting parsedatetime>=1.2 (from jrnl)
  Using cached parsedatetime-2.3-py2-none-any.whl
Collecting pytz>=2013b (from jrnl)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting keyring>=3.3 (from jrnl)
  Using cached keyring-10.3.2-py2.py3-none-any.whl
Collecting six>=1.6.1 (from jrnl)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting future (from parsedatetime>=1.2->jrnl)
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring>=3.3->jrnl)
Collecting cryptography (from secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
Collecting idna>=2.1 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting enum34 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting setuptools>=11.3 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached setuptools-35.0.2-py2.py3-none-any.whl
Collecting ipaddress (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting packaging (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools>=11.3->cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
Collecting pyparsing (from packaging->cryptography->secretstorage; sys_platform == "linux2" or sys_platform == "linux"->keyring>=3.3->jrnl)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: python-dateutil, pytz, tzlocal, future, parsedatetime, idna, enum34, six, appdirs, pyparsing, packaging, setuptools, ipaddress, pycparser, cffi, asn1crypto, cryptography, secretstorage, keyring, jrnl
Successfully installed appdirs-1.4.3 asn1crypto-0.22.0 cffi-1.10.0 cryptography-1.8.1 enum34-1.1.6 future-0.16.0 idna-2.5 ipaddress-1.0.18 jrnl-1.9.8 keyring-10.3.2 packaging-16.8 parsedatetime-2.3 pycparser-2.17 pyparsing-2.2.0 python-dateutil-1.5 pytz-2017.2 secretstorage-2.3.1 setuptools-35.0.2 six-1.10.0 tzlocal-1.4
```

But when I run `jrnl` or any other related command: `jrnl: command not found`. I can't tell what's wrong at all.

**Comment by maebert** [comment]
That's interesting. Could you answer a few questions for me to help with this issue?

1. Which OS are you using
2. If macOS, are you using the built-in python, or the one installed with homebrew?
2. What's the output of `python --version`
3. What's the output of `pip --version`?
4. What's the output of `python -c "import jrnl; print(jrnl.__version__)"`?

Thanks!

**Comment by undying-fish** [comment]
1. Lubuntu Linux, though I've riced it some. Running in i3 with xfce4-terminal and fish.
2. N/A
3. Python 2.7.13
4. pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
5. 1.9.8

For the record it isn't a problem with fish, as running `jrnl` in bash returns the same.

**Comment by maebert** [comment]
That's odd indeed. What should have happened during installation is that a python script called `jrnl` gets created in `/usr/local/bin/` (possibly somewhere else on your platform). You could try `sudo find / -name jrnl` to see if it maybe ended up somewhere else where your shell is not looking for it (you should at least find the module itself, probably somewhere in `/usr/lib/python2.7/site-packages/jrnl`)

Alternatively, you can just create it (e.g. in `~/bin/`) with these contents:

```python
#!/usr/bin/env python2.7
# EASY-INSTALL-ENTRY-SCRIPT: 'jrnl','console_scripts','jrnl'
__requires__ = 'jrnl'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('jrnl', 'console_scripts', 'jrnl')()
    )
```

**Comment by undying-fish** [comment]
Turns out it's in `~/.local/bin/jrnl`. That's not in my `$PATH`, which could explain things. I suppose moving it directly to `/usr/local/bin/` should render this solved? The module itself was in `~/.local/lib/...` rather than `/usr/lib/...`. Any hints as to why it got installed to those directories?

The only real pointer I've got was that I probably used the [install script in my dotfiles](https://github.com/undying-fish/.files/blob/master/install.sh), so maybe having root access got to its head, if you know what I mean...

**Comment by maebert** [comment]
Hm, possible. Alternatively you could just put `~/.local/bin/` into your `$PATH` of course, in case your pip would like to install more things over there for some reason.

Glad we solved this mystery, closing the ticket as it sounds it's a setup-specific issue. Let me know if you need any more help!

**Comment by ngminhtrung** [comment]
Hi @maebert , 

I've encountered the same isssue with @boardfish `jrnl: command not found`.  I tried to detect and resolve the issue but no luck at all. 

***My way of installation** (Reference: http://www.linux-magazine.com/Online/Blogs/Productivity-Sauce/Keep-Journal-with-jrnl)
```
git clone git://github.com/maebert/jrnl.git
cd jrnl
python setup.py install
```

For your **questions**:
1. Which OS are you using:
Linux Mint Cinnamon 18.3 64bit
2. If macOS, are you using the built-in python, or the one installed with homebrew?
N/A
3. What's the output of python --version
Python 2.7.12
4. What's the output of pip --version?
pip 9.0.1 from /home/ngminhtrung/.local/lib/python2.7/site-packages (python 2.7)
5. What's the output of python -c "import jrnl; print(jrnl.__version__)"?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jrnl/__init__.py", line 16, in <module>
    from . import Journal
  File "/usr/local/lib/python2.7/dist-packages/jrnl/Journal.py", line 6, in <module>
    from . import util
  File "/usr/local/lib/python2.7/dist-packages/jrnl/util.py", line 6, in <module>
    import keyring
ImportError: No module named keyring
```
Then I searched for `jrnl` in my system via `sudo find / -name jrnl`, the result is:
```
/jrnl
/jrnl/jrnl
/jrnl/build/lib.linux-x86_64-2.7/jrnl
/jrnl/docs/_themes/jrnl
/usr/local/lib/python2.7/dist-packages/jrnl
```
Then added `/usr/local/lib` to my $PATH, error is still there. 

Do you have any advice for me? Thanks in advance.

**Comment by Granddave** [comment]
I got the same error as @boardfish and by reading this issue I realized that I did not run `pip install jrnl` as root, which led to an installation in my `~/.local/` instead of `/usr/local/`. So I thought I leave this here for future reference.
Running Debian 9.

**Comment by boardfish** [comment]
What I'd recommend is installing pyenv, then running the following:

```
pyenv install 3.6.3 # or whatever's the latest
pyenv global 3.6.3
```

...then use `pip` to install as usual. Using `python` in a virtual environment rather than using the system `python` (or any language, really - there's also `rvm` and `nvm` for Ruby and Node respectively, plus `stack` for Haskell) saves you ruining permissions by running pip as root.
