### ISSUE TITLE
Journal gets emptied if it does not fit data format

### ISSUE THREAD

**Issue by rolandu** [maebert/jrnl#490]
Hi,

It appears that when saving a new entry, everything before the first correctly formatted entry gets deleted. This seems quite dangerous.

Steps to reproduce (Option 1):

- Create journal with a couple of entries
- Insert text on top of file
- "jrnl new entry"
- Text on top is now deleted.
- Expected: Text should stay there or I should get an error message or question.

Steps to reproduce (Option 2):

- Use an existing journal file from another application (or hand-written text)
- "jrnl new entry"
- All text except "new entry" deleted
- Expected: My text should stay there.

Steps to reproduce (Option 3):

- Use jrnl to create journal
- Change the date format in .jrnl_config
- "jrnl new entry"
- All text except "new entry" deleted
- Expected: Old entries should stay there or be converted to the new format...

**Comment by maebert** [comment]
Hey @rolandu,

I'm sadly aware of that. It's fixed in version 2.0, but there are quite a few open tasks for that release.
