### ISSUE TITLE
Markdown Export Comma btwn Dates and Title

### ISSUE THREAD

**Issue by insanerwayner** [maebert/jrnl#497]
Is there a way to remove the comma between the Date and the Title when exporting to Markdown?
Example:
### 2017-08-14 18:17, First Night On-Call
Here's the conversion to markdown in **exporters.py** file.

```
def to_md(journal):
    """Returns a markdown representation of the Journal"""
    out = []
    year, month = -1, -1
    for e in journal.entries:
        if not e.date.year == year:
            year = e.date.year
            out.append(str(year))
            out.append("=" * len(str(year)) + "\n")
        if not e.date.month == month:
            month = e.date.month
            out.append(e.date.strftime("%B"))
            out.append('-' * len(e.date.strftime("%B")) + "\n")
        out.append(e.to_md())
    result = "\n".join(out)
return result
```
Not seeing where the comma is coming from.

**Comment by stelabr** [comment]
After a bit of digging, it seems this code simply generated the year and month headers. When `out.append(e.to_md())` is called, the post is sent to to the `to_md()` function, which formats the post body.
https://github.com/maebert/jrnl/blob/919094c2568638da6775b6291a070cea857020d3/jrnl/Entry.py#L105
