### ISSUE TITLE
jrnl is not working properly (for me)

### ISSUE THREAD

**Issue by BoundlessCarrot** [maebert/jrnl#510]
So, I installed jrnl today and tried to set it up. It asked me where I wanted to put the .txt file, and I put in Desktop/WIP, which is a folder on my desktop. It asked if I wanted to encrypt the file. I said yes, but an error occurred when I wanted to store the password in my keychain. 

Anyway, when I try to submit an entry, my terminal spits out this message:
[Error: Desktop/WIP is a directory, but doesn't seem to be a DayOne journal either.

I tried looking for the config file, but I couldn't find it. What does this error mean and how can i fix it?

**Comment by maebert** [comment]
Interesting. Can you share the contents of your config file (in `~/.jrnl_config` or `~/.config/jrnl/...`)?

**Comment by BoundlessCarrot** [comment]
Sorry it's a screenshot.

**Comment by anteante** [comment]
Same problem here:

[Error: /Users/lucas/Documents/jrnl is a directory, but doesn't seem to be a DayOne journal either.

My .jrnl_config file:

```
{
  "default_hour": 9, 
  "timeformat": "%Y-%m-%d %H:%M", 
  "linewrap": 79, 
  "encrypt": false, 
  "editor": "/usr/bin/nano", 
  "default_minute": 0, 
  "highlight": true, 
  "journals": {
    "default": "/Users/lucas/Documents/jrnl"
  }, 
  "tagsymbols": "@"
}
```

**Comment by stelabr** [comment]
New to the project, but I'm pretty sure individual journals are stored as a single files. If you specify a directory in your config, jrnl will try to open it as a Day-One journal.

So if you're not using jrnl for Day-One, point your journal parameter in the config to a file like `Desktop/WIP/journal.txt`

[Relevant code block](https://github.com/maebert/jrnl/blob/919094c2568638da6775b6291a070cea857020d3/jrnl/cli.py#L191)
