### ISSUE TITLE
[feature request] Possibility to define templates for notes

### ISSUE THREAD

**Issue by jottr** [maebert/jrnl#511]
Let's say I want to quickly create notes with the same structure: 

```
# Problem
 
# Approach

# Solution
```

It would be quite helpful to specify a template file for notes.

**Comment by iamlukesky** [comment]
There's [this](http://jrnl.sh/recipes.html?highlight=template#using-templates) about templates in the docs. I think may not be exactly what I would like it to be. Doing the `jrnl -1 --edit` looks cumbersome. I would like to define a template file in my config and have my external editor open to that file when typing `jrnl`.

**Comment by jottr** [comment]
Thanks for pointing this out.
I might be able to work with this. 
Definining a template file in the config would be the more elegant and convenient route IMHO.

**Comment by iamlukesky** [comment]
I tried it out and ended up adding an alias to my `.bashrc`, like so:

`alias journal="jrnl < ~/journaltemplate.txt && jrnl -1 --edit"`

journaltemplate.txt:
```
\n# Template heading 1

# Template heading 2
```

The `\n` is needed to place the jrnl timestamp and the heading on different rows.
