### ISSUE TITLE
Specifying different journal file?

### ISSUE THREAD

**Issue by willprice** [maebert/jrnl#522]
Hi,

Is it possible to specify an alternate journal file on the command line as I'd like to keep multiple journals: e.g. one for work, one for personal etc.

Looking through the docs I can't see any details on how to achieve this.

**Comment by stelabr** [comment]
http://jrnl.sh/advanced.html#multiple-journal-files

**Comment by willprice** [comment]
Apologies for not searching hard enough, thanks for the link!

**Comment by stelabr** [comment]
@willprice No problem!
