### ISSUE TITLE
Can't set a directory with a space in the name

### ISSUE THREAD

**Issue by charliesneath** [maebert/jrnl#537]
I'm having trouble setting the JRNL location to be my `~/Dropbox (Personal)/jrnl` folder. Escaping the characters and adding quotes are taken as text symbols and creates a new folder.

What's the proper way to set the location in my `.jrnl_config` file?

**Comment by charliesneath** [comment]
I fixed the issue. I wasn't including the filename when typing in a new location.

**Comment by cwalo** [comment]
@charliesneath I'm trying to do the same, but even pointing to the file in my Dropbox folder leads to the creation of a new folder. Mind sharing your jrnl_config file?

**Comment by cwalo** [comment]
I ran into this as well. If anyone else reads this, you should not escape the path in `jrnl_config`:
```
...
"default": "/Users/username/Dropbox (Personal)/Journals/journal.txt"
...
```
