### ISSUE TITLE
`keyring` package should be optional as cryptography

### ISSUE THREAD

**Issue by kuzzmi** [maebert/jrnl#546]
Hey,

I'm using jrnl on my desktops for quite a while and wanted to install it on my Android device (within Termux app). I have all dependencies installed, except for `cffi` which fails and I have some weird issues with installing `cryptography` package. What caught my eye is that despite me not wanting to deal with encryption in this particular case at all, I still have to.
I imagine that `cffi` is a part of a `cryptography` package and fails due to some missing compatible compiler, but by being a requirement I can't install `jrnl` in otherwise normal environment.

**Comment by kuzzmi** [comment]
After some investigation, I found that jrnl depends on `cryptography` package through a `keyring` package which actually should be optional the same way as other crypto packages are.

**Comment by maebert** [comment]
This is fix in 2.0, which we'll hope to release for everybody soon!
