### ISSUE TITLE
Feature Request: Automatically display journal entries using a pager (like less)

### ISSUE THREAD

**Issue by abrahamneben** [maebert/jrnl#548]
It would be great if there were a jrnl setting that sets it to automatically pipe jrnl entries to less when displaying them. Then I wouldn't have to clear my entire terminal output after just reading a past entry.

**Comment by maebert** [comment]
jrnl is meant to play nicely with other command line tools, so I'd recommend just creating a bash alias for that, like `alias lrnl="jrnl -n 1 | less"`
