### ISSUE TITLE
timeformat parameter changes to config file have no effect

### ISSUE THREAD

**Issue by rrblocker** [maebert/jrnl#551]
Hi,
I'm using jrnl version 1.9.8 on Ubuntu 18.04. When I edit my ~/.jrnl_config file and change the default timeformat to this:

  "timeformat": "%a, %d %b %Y %H:%M",

it has no effect. The date still shows as: 2018-07-25 07:42. I tried a few other formats as well, but none displayed the desired changes.

**Comment by maebert** [comment]
This will be fixed in 2.0 - In short, in 1.x changing the config file will only change how the dates are *parsed* from the journal file, and will not actually update your journal file itself.
