### ISSUE TITLE
Issue with accents

### ISSUE THREAD

**Issue by Terenziof93** [maebert/jrnl#552]
I am writing my journal in Italian. I often use accented letters (e.g. "à", "è", "ò"), but when I ask the program to show me the previous entries the accented letters are displayed improperly. There is any way to solve this problem without using an external editor?

Edit: I solved it typing `jrnl : my post`. It persist when I use the built-in editor of the command typing `jrnl [return] my post`.

**Comment by YohannLYD** [comment]
In case other run into the same problem, setting vim as my text editor in the config file solved it for me. Setting nano or any other text editor should  do the trick.

This could be useful to mention in the documentation/website for special characters users.
