### ISSUE TITLE
Multiple tagsymbols

### ISSUE THREAD

**Issue by sjdennis** [maebert/jrnl#559]
Is it possible to define multiple tagsymbols? I would like to use both + and @ as tagsymbols, as I am using a task tracking system in todo.txt that uses both projects (+) and contexts (@), and would like to be able to refer to both in jrnl using the same symbology, so that I can take quick notes in either tool without having to consider which software I am working in and write accordingly.

If so, how would I modify the relevant line in ~/.jrnl_config? I've tried to edit this to define two tagsymbols, but without success.

**Comment by philipsd6** [comment]
Sure is, but you should be using Jrnl 2.0... Not sure this works in v1. I have the following in my `~/.config/jrnl/jrnl.yaml` file:

```yaml
tagsymbols: '@#^%'
# @ is for People
# # is for Tags
# ^ is for Places
# % is for Moods/Emotions
```

**Comment by dvancamp** [comment]
In Jrnl 1.9.8 homebrew, this format works.
`"tagsymbols": "@,#,^,%",`
