### ISSUE TITLE
Shouldn't jrnl prompt for your key when you view entries? 

### ISSUE THREAD

**Issue by testingwithfire** [maebert/jrnl#574]
I just installed jrnl and chose to encrypt my entries.

If I open journal.txt with a regular editor, the file appears to be encrypted. 

However, if I enter "jrnl -n 10", I get a list of entries. I am not prompted for the key I chose when I first ran jrnl.

As a result, all someone has to do to view my entries is to know that I use jrnl to make them. This is not very likely, but it's possible.

**Comment by maebert** [comment]
During setup, you have probable chosen to store the password in your keychain. Re-running `jrnl encrypt` should reset this behaviour.
