### ISSUE TITLE
No handlers could be found for logger "keyring.backend"

### ISSUE THREAD

**Issue by northern-arizona** [maebert/jrnl#579]
I installed jrnl on my Ubuntu Budgie (Ubuntu 18.04 LTS) machine, using `pip install jrnl`.

When I run jrnl, I get this error:

> No handlers could be found for logger "keyring.backend"

No entries get recorded into my journal. I'd like to fix this error message.
Any thoughts?

**Comment by Hrafnthor** [comment]
Have you attempted to run 'pip install --upgrade keyrings.alt'?

**Comment by northern-arizona** [comment]
That worked! jrnl is working now!

Thanks!
