### ISSUE TITLE
2.0-rc1: YAMLLoadWarning

### ISSUE THREAD

**Issue by wren** [maebert/jrnl#584]
First of all, thanks for the code! This project really has a lot of promise.

I was exploring the `2.0-rc1` branch, and I get this warning when doing any command (including `jnrl --version`).

```
jrnl/plugins/template.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

It looks like there are a few calls that use the older style of calling `yaml.load`.

**Comment by maebert** [comment]
Thanks for the PR!
